Name: Recipe
Id: g=f7c13b323a8361859b282e563434e6a1
Type: FolderType
Children:
- Name: Ingredient01
  Type: BaseDataVariableType
  DataType: Int32
- Name: Ingredient02
  Type: BaseDataVariableType
  DataType: Int32
- Name: Ingredient03
  Type: BaseDataVariableType
  DataType: Int32
